language: python

python:
 - 3.6
 - 3.5
 - 3.7

before_install:
 - wget http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data


script:
 - python3 kmeans_iris.py --help
 - python3 kmeans_iris.py iris.data

